package net.azisaba.vanilife.housing

import net.azisaba.packed.font.PackFont
import net.azisaba.packed.font.provider.PackBitmapFontProvider
import net.azisaba.packed.util.dsl.packed
import net.azisaba.packed.util.ktor.ResourcePackRequestSender
import net.azisaba.packed.util.ktor.launchKtor
import net.kyori.adventure.text.Component

internal fun Main.setupPacked() {
    val pack = packed {
        metadata {
            minFormat(65)
            maxFormat(65)
            describe(Component.text("Auto generated by ${pluginMeta.name}"))
        }

        plugins {
            +this@setupPacked
        }

        namespace(this@setupPacked) {
            font {
                HousingFonts.WAVES(
                    PackFont(
                        listOf(
                            PackBitmapFontProvider(
                                key("large_0.png"),
                                listOf("${HousingFonts.WavesCharCodes.LARGE_0}"),
                                767,
                                768,
                            )
                        )
                    )
                )
            }
        }
    }

    pack.launchKtor(
        this,
        port = 8081,
        resourcePackRequestSender = ResourcePackRequestSender.Simple(),
    )
}
