[versions]
kotlin = "2.3.0"
kotlinx-coroutines = "1.10.2"

shadow = "9.3.1"

koin = "4.1.1"
tomlkt = "0.6.0"
mccoroutine = "2.22.0"
packetevents = "2.11.2"
entitylib = "3.0.3-SNAPSHOT"
bettermodel = "2.1.0"
packed = "0.0.0"

exposed = "1.0.0"
hikaricp = "7.0.2"
postgresql = "42.7.10"

[plugins]
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }

[libraries]
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
tomlkt = { module = "dev.eav.tomlkt:tomlkt", version.ref = "tomlkt" }
mccoroutine-folia-api = { module = "com.github.shynixn.mccoroutine:mccoroutine-folia-api", version.ref = "mccoroutine" }
mccoroutine-folia-core = { module = "com.github.shynixn.mccoroutine:mccoroutine-folia-core", version.ref = "mccoroutine" }
packetevents = { module = "com.github.retrooper:packetevents-spigot", version.ref = "packetevents" }
entitylib = { module = "io.github.tofaa2:spigot", version.ref = "entitylib" }
bettermodel-bukkit-api = { module = "io.github.toxicity188:bettermodel-bukkit-api", version.ref = "bettermodel" }
packed = { module = "net.azisaba:packed", version.ref = "packed" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
hikaricp = { module = "com.zaxxer:HikariCP", version.ref = "hikaricp" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
