[versions]
bettermodel = "2.1.0"
entitylib = "3.0.3-SNAPSHOT"
exposed = "1.0.0"
hikaricp = "7.0.2"
jnoise = "4.1.0"
koin = "4.1.1"
kotlin = "2.3.0"
kotlinx-coroutines = "1.10.2"
mccoroutine = "2.22.0"
packed = "1.0.0-R0.2-SNAPSHOT"
packetevents = "2.11.2"
paperweight = "2.0.0-beta.19"
postgresql = "42.7.10"
shadow = "9.3.1"
tomlkt = "0.6.0"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
paperweight-patcher = { id = "io.papermc.paperweight.patcher", version.ref = "paperweight" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }

[libraries]
# Language
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }

# Dependency Injection (DI)
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }

# Minecraft
bettermodel-bukkit-api = { module = "io.github.toxicity188:bettermodel-bukkit-api", version.ref = "bettermodel" }
entitylib = { module = "io.github.tofaa2:spigot", version.ref = "entitylib" }
mccoroutine-folia-api = { module = "com.github.shynixn.mccoroutine:mccoroutine-folia-api", version.ref = "mccoroutine" }
mccoroutine-folia-core = { module = "com.github.shynixn.mccoroutine:mccoroutine-folia-core", version.ref = "mccoroutine" }
packed-core = { module = "net.azisaba.packed:core", version.ref = "packed" }
packed-resource = { module = "net.azisaba.packed:resource", version.ref = "packed" }
packed-server = { module = "net.azisaba.packed:server", version.ref = "packed" }
packetevents = { module = "com.github.retrooper:packetevents-spigot", version.ref = "packetevents" }

# Database
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
hikaricp = { module = "com.zaxxer:HikariCP", version.ref = "hikaricp" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }

# Utility
jnoise-pipeline = { module = "de.articdive:jnoise-pipeline", version.ref = "jnoise" }
tomlkt = { module = "dev.eav.tomlkt:tomlkt", version.ref = "tomlkt" }
