name: Patch and Build

on:
  push:
    branches: [ "**" ]

jobs:
  build:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Configure Git User Details
        run: git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"

      - name: Apply Patches
        run: ./gradlew applyPatches

      - name: Build
        run: ./gradlew build

      - name: Jar
        run: ./gradlew createMojmapPaperclipJar

      - name: Upload JAR to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: build/libs/*.jar
          prerelease: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
